PREP(action_fusebox);
PREP(createFuseboxActions);
PREP(condition);
PREP(condition_fusebox);
PREP(condition_off);
PREP(condition_on);
PREP(ensureFuseboxHelper);
PREP(fadeFuseboxHelper);
PREP(server_setBuildingMainSwitch);
