#define DIRECTCONNECT_IDC_PASSWORDTEXT 1008
#define DIRECTCONNECT_IDC_PASSWORD     1009

// =============================================================================

#define CENTER(PARENT_SIZE, CHILD_SIZE) ((PARENT_SIZE / 2) - (CHILD_SIZE / 2))

#define DIRECTCONNECT_XSCALE           (((safezoneW / safezoneH) min 1.2) / 40)
#define DIRECTCONNECT_YSCALE           ((((safezoneW / safezoneH) min 1.2) / 1.2) / 25)

#define DIRECTCONNECT_TOTALW           (30 * DIRECTCONNECT_XSCALE)
#define DIRECTCONNECT_TOTALH           (10 * DIRECTCONNECT_YSCALE)
#define DIRECTCONNECT_SPACERY          (0.12 * DIRECTCONNECT_YSCALE)
#define DIRECTCONNECT_ELEMENTH         (1 * DIRECTCONNECT_YSCALE)
#define DIRECTCONNECT_PADDINGY         (1 * DIRECTCONNECT_YSCALE)
#define DIRECTCONNECT_PADDINGX         (1 * DIRECTCONNECT_XSCALE)
#define DIRECTCONNECT_TEXTBOXH         (2* DIRECTCONNECT_XSCALE)
#define DIRECTCONNECT_BUTTONW          (6.25 * DIRECTCONNECT_XSCALE)

#define DIRECTCONNECT_MAINH            (DIRECTCONNECT_TOTALH - 2*DIRECTCONNECT_ELEMENTH - 2*DIRECTCONNECT_SPACERY)

#define DIRECTCONNECT_TOTALX           (CENTER(1,DIRECTCONNECT_TOTALW))
#define DIRECTCONNECT_TOTALY           (CENTER(1,DIRECTCONNECT_TOTALH))
#define DIRECTCONNECT_MAINY            (DIRECTCONNECT_TOTALY + DIRECTCONNECT_ELEMENTH + DIRECTCONNECT_SPACERY)

#define DIRECTCONNECT_CONTENTW         (DIRECTCONNECT_TOTALW - 2*DIRECTCONNECT_PADDINGX)
#define DIRECTCONNECT_CONTENTX         (DIRECTCONNECT_TOTALX + DIRECTCONNECT_PADDINGX)
#define DIRECTCONNECT_BUTTONOKX        (DIRECTCONNECT_TOTALX + DIRECTCONNECT_TOTALW - DIRECTCONNECT_BUTTONW)
#define DIRECTCONNECT_BUTTONY          (DIRECTCONNECT_MAINY + DIRECTCONNECT_MAINH + DIRECTCONNECT_SPACERY)

#define DIRECTCONNECT_X                (safeZoneX + 2 * DIRECTCONNECT_XSCALE)
#define DIRECTCONNECT_LOGOX            (DIRECTCONNECT_X - (1.8 * (pixelH * pixelGrid * 2)))
