#define GRAD_DIRECTCONNECT_IDC_PASSWORDTEXT 1008
#define GRAD_DIRECTCONNECT_IDC_PASSWORD     1009

// =============================================================================

#define CENTER(PARENT_SIZE, CHILD_SIZE) ((PARENT_SIZE / 2) - (CHILD_SIZE / 2))

#define GRAD_DIRECTCONNECT_XSCALE           (((safezoneW / safezoneH) min 1.2) / 40)
#define GRAD_DIRECTCONNECT_YSCALE           ((((safezoneW / safezoneH) min 1.2) / 1.2) / 25)

#define GRAD_DIRECTCONNECT_TOTALW           (30 * GRAD_DIRECTCONNECT_XSCALE)
#define GRAD_DIRECTCONNECT_TOTALH           (10 * GRAD_DIRECTCONNECT_YSCALE)
#define GRAD_DIRECTCONNECT_SPACERY          (0.12 * GRAD_DIRECTCONNECT_YSCALE)
#define GRAD_DIRECTCONNECT_ELEMENTH         (1 * GRAD_DIRECTCONNECT_YSCALE)
#define GRAD_DIRECTCONNECT_PADDINGY         (1 * GRAD_DIRECTCONNECT_YSCALE)
#define GRAD_DIRECTCONNECT_PADDINGX         (1 * GRAD_DIRECTCONNECT_XSCALE)
#define GRAD_DIRECTCONNECT_TEXTBOXH         (2* GRAD_DIRECTCONNECT_XSCALE)
#define GRAD_DIRECTCONNECT_BUTTONW          (6.25 * GRAD_DIRECTCONNECT_XSCALE)

#define GRAD_DIRECTCONNECT_MAINH            (GRAD_DIRECTCONNECT_TOTALH - 2*GRAD_DIRECTCONNECT_ELEMENTH - 2*GRAD_DIRECTCONNECT_SPACERY)

#define GRAD_DIRECTCONNECT_TOTALX           (CENTER(1,GRAD_DIRECTCONNECT_TOTALW))
#define GRAD_DIRECTCONNECT_TOTALY           (CENTER(1,GRAD_DIRECTCONNECT_TOTALH))
#define GRAD_DIRECTCONNECT_MAINY            (GRAD_DIRECTCONNECT_TOTALY + GRAD_DIRECTCONNECT_ELEMENTH + GRAD_DIRECTCONNECT_SPACERY)

#define GRAD_DIRECTCONNECT_CONTENTW         (GRAD_DIRECTCONNECT_TOTALW - 2*GRAD_DIRECTCONNECT_PADDINGX)
#define GRAD_DIRECTCONNECT_CONTENTX         (GRAD_DIRECTCONNECT_TOTALX + GRAD_DIRECTCONNECT_PADDINGX)
#define GRAD_DIRECTCONNECT_BUTTONOKX        (GRAD_DIRECTCONNECT_TOTALX + GRAD_DIRECTCONNECT_TOTALW - GRAD_DIRECTCONNECT_BUTTONW)
#define GRAD_DIRECTCONNECT_BUTTONY          (GRAD_DIRECTCONNECT_MAINY + GRAD_DIRECTCONNECT_MAINH + GRAD_DIRECTCONNECT_SPACERY)
