# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ACE SQF validator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        wget https://raw.githubusercontent.com/acemod/ACE3/b181fa6013d30a06b310b367caa5039435b085d0/tools/sqf_validator.py
        sed -i '117d' sqf_validator.py
        sed -i '116d' sqf_validator.py
        sed -i '115d' sqf_validator.py
    - name: Lint
      run: |
        python3 sqf_validator.py
