name: SQF linting (LordGolias/sqf)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install sqflint
      run: |
        python -m pip install --upgrade pip
        python -m pip install https://github.com/gruppe-adler/sqf/archive/based-on-jokoho.tar.gz
    - name: Lint with
      run: |
        sqflint -d . -e e

