#define VERSIONCHECK_TOTALW            (safezoneW / 4)
#define VERSIONCHECK_TOTALH            (safeZoneH / 3)

#define VERSIONCHECK_TOTALX            (safeZoneX + (safeZoneW / 2) - (VERSIONCHECK_TOTALW / 2))
#define VERSIONCHECK_TOTALY            (safeZoneY + (safeZoneH / 2) - (VERSIONCHECK_TOTALH / 2))

#define VERSIONCHECK_TITLEH            (1 * ((((safezoneW / safezoneH) min 1.2) / 1.2) / 25))
#define VERSIONCHECK_SPACERY           (safeZoneH / 500)

#define VERSIONCHECK_TEXTY             (VERSIONCHECK_TOTALY + VERSIONCHECK_TITLEH + VERSIONCHECK_SPACERY)
#define VERSIONCHECK_TEXTH             (VERSIONCHECK_TOTALH - 2 * VERSIONCHECK_TITLEH - 2 * VERSIONCHECK_SPACERY)

#define VERSIONCHECK_BUTTONW           (6.25 * (((safezoneW / safezoneH) min 1.2) / 40))
#define VERSIONCHECK_BUTTONX           (VERSIONCHECK_TOTALX + VERSIONCHECK_TOTALW - VERSIONCHECK_BUTTONW)
#define VERSIONCHECK_BUTTONY           (VERSIONCHECK_TEXTY + VERSIONCHECK_TEXTH + VERSIONCHECK_SPACERY)
