#define GRAD_VERSIONCHECK_TOTALW            (safezoneW / 4)
#define GRAD_VERSIONCHECK_TOTALH            (safeZoneH / 3)

#define GRAD_VERSIONCHECK_TOTALX            (safeZoneX + (safeZoneW / 2) - (GRAD_VERSIONCHECK_TOTALW / 2))
#define GRAD_VERSIONCHECK_TOTALY            (safeZoneY + (safeZoneH / 2) - (GRAD_VERSIONCHECK_TOTALH / 2))

#define GRAD_VERSIONCHECK_TITLEH            (1 * ((((safezoneW / safezoneH) min 1.2) / 1.2) / 25))
#define GRAD_VERSIONCHECK_SPACERY           (safeZoneH / 500)

#define GRAD_VERSIONCHECK_TEXTY             (GRAD_VERSIONCHECK_TOTALY + GRAD_VERSIONCHECK_TITLEH + GRAD_VERSIONCHECK_SPACERY)
#define GRAD_VERSIONCHECK_TEXTH             (GRAD_VERSIONCHECK_TOTALH - 2 * GRAD_VERSIONCHECK_TITLEH - 2 * GRAD_VERSIONCHECK_SPACERY)

#define GRAD_VERSIONCHECK_BUTTONW           (6.25 * (((safezoneW / safezoneH) min 1.2) / 40))
#define GRAD_VERSIONCHECK_BUTTONX           (GRAD_VERSIONCHECK_TOTALX + GRAD_VERSIONCHECK_TOTALW - GRAD_VERSIONCHECK_BUTTONW)
#define GRAD_VERSIONCHECK_BUTTONY           (GRAD_VERSIONCHECK_TEXTY + GRAD_VERSIONCHECK_TEXTH + GRAD_VERSIONCHECK_SPACERY)
